inherit_gem:
  google-style: google-style.yml

AllCops:
  Exclude:
    - "acceptance/**/*"
    - "support/**/*"
    - "google-cloud-spanner.gemspec"
    - "Rakefile"
    - "test/**/*"
    - "benchmark/**/*"
    - "vendor/**/*"

Documentation:
  Enabled: false

Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Exclude:
    - "lib/google/cloud/spanner.rb"
Metrics/PerceivedComplexity:
  Exclude:
    - "lib/google/cloud/spanner.rb"
Naming/FileName:
  Exclude:
    - "lib/google-cloud-spanner.rb"
Style/SymbolArray:
  Enabled: false
Style/WordArray:
  Enabled: false
